# Generated by Django 5.0 on 2023-12-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='последнее изменение'),
        ),
    ]
