# Generated by Django 5.0 on 2023-12-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='последнее изменение'),
        ),
    ]
