# Generated by Django 4.0 on 2023-10-04 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='наименование', max_length=100, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='last_modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='последнее изменение'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='наименование', max_length=100, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='превью'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
