# Generated by Django 5.0 on 2024-02-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.FloatField(verbose_name='номер версии'),
        ),
    ]
